### ISSUE TITLE
Cannot find module 'unist-util-is/lib/index.js' or its corresponding type declarations

### ISSUE THREAD

**Issue by talatkuyuk** [syntax-tree/unist-util-visit#36]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unist-util-visit@4.1.2

### Steps to reproduce

After upgrading from 4.1.1 to 4.1.2 I receive the errors below:

> remark-flexible-code-titles@1.0.7 build:esm
> tsc

node_modules/unist-util-visit/lib/index.d.ts:32:24 - error TS2307: Cannot find module 'unist-util-is/lib/index.js' or its corresponding type declarations.

32   Check extends import('unist-util-is/lib/index.js').Test
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unist-util-visit/lib/index.d.ts:115:24 - error TS2307: Cannot find module 'unist-util-is/lib/index.js' or its corresponding type declarations.

115   Check extends import('unist-util-is/lib/index.js').Test
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unist-util-visit/lib/index.d.ts:132:24 - error TS2307: Cannot find module 'unist-util-is/lib/index.js' or its corresponding type declarations.

132   Check extends import('unist-util-is/lib/index.js').Test = string

### Expected behavior

No type declaration errors.

### Actual behavior

Receive type declaration errors.

### Affected runtime and version

node@16.15.0

### Affected package manager and version

npm@8.5.5

### Affected OS and version

macos

**Comment by wooorm** [comment]
If you throw away your `node_modules` and package locks, and install again, it should be fixed.

**Comment by wooorm** [comment]
You can see that they are published to npm:
- https://www.npmjs.com/package/unist-util-visit?activeTab=explore
- https://www.npmjs.com/package/unist-util-is?activeTab=explore

**Comment by talatkuyuk** [comment]
Got it. After removing `node_modules`, and re-installing the packages, fixed the issue.

Thanks @wooorm

**Comment by wooorm** [comment]
Cool :)
